
[[redirects]]
from = "https://indeps.netlify.com/*"
to = "/publicodes.html"
status = 200
# InFrance PRODUCTION settings 

[[redirects]]
from = "https://mycompanyinfrance.fr/robots.txt"
to = "/robots.infrance.txt"
status = 200

[[redirects]]
from = "https://mycompanyinfrance.fr/sitemap.txt"
to = "/sitemap.infrance.en.txt"
status = 200

[[redirects]]
from = "https://mycompanyinfrance.fr"
to = "/prerender/infrance/index.html"
status = 200

[[redirects]]
from = "https://mycompanyinfrance.fr/social-security"
to = "/prerender/infrance/social-security/index.html"
status = 200

[[redirects]]
from = "https://mycompanyinfrance.fr/*"
to = "/infrance.html"
status = 200

# Mon-entreprise.beta PRODUCTION settings (temporary)
[[redirects]]
from = "https://mon-entreprise.beta.gouv.fr/robots.txt"
to = "/robots.infrance.txt"
status = 200

[[redirects]]
from = "https://mon-entreprise.beta.gouv.fr/sitemap.txt"
to = "/sitemap.infrance.fr.txt"
status = 200

[[redirects]]
from = "https://mon-entreprise.beta.gouv.fr"
to = "/prerender/mon-entreprise/index.html"
status = 200

[[redirects]]
from = "https://mon-entreprise.beta.gouv.fr/sécurité-sociale"
to = "/prerender/mon-entreprise/sécurité-sociale/index.html"
status = 200

[[redirects]]
from = "https://mon-entreprise.beta.gouv.fr/*"
to = "/mon-entreprise.html"
status = 200


# Mon-entreprise.fr PRODUCTION settings
[[redirects]]
from = "https://mon-entreprise.fr/robots.txt"
to = "/robots.infrance.txt"
status = 200

[[redirects]]
from = "https://mon-entreprise.fr/sitemap.txt"
to = "/sitemap.infrance.fr.txt"
status = 200

[[redirects]]
from = "https://mon-entreprise.fr"
to = "/prerender/mon-entreprise/index.html"
status = 200

[[redirects]]
from = "https://mon-entreprise.fr/sécurité-sociale"
to = "/prerender/mon-entreprise/sécurité-sociale/index.html"
status = 200

[[redirects]]
from = "https://mon-entreprise.fr/*"
to = "/mon-entreprise.html"
status = 200


# Embauche PRODUCTION settings
[[redirects]]
from = "https://embauche.beta.gouv.fr/stats"
to = "https://rough-college.glitch.me/"
status = 200

[[redirects]]
from = "https://embauche.beta.gouv.fr/modules/v2/*"
to = "/:splat"

[[redirects]]
from = "https://embauche.beta.gouv.fr/robots.txt"
to = "/robots.embauche.txt"
status = 200

[[redirects]]
from = "https://embauche.beta.gouv.fr/"
to = "/prerender/embauche/index.html"
status = 200

[[redirects]]
from = "https://embauche.beta.gouv.fr/*"
to = "/embauche.html"
status = 200

# Redirect for embauche in staging and development settings
[[redirects]]
from = "/"
query = {s = "e"}
to = "/prerender/embauche/index.html"
status = 200

[[redirects]]
from = "/*"
query = {s = "e"}
to = "/embauche.html"
status = 200

# Redirect to mycompanyinfrance in staging and development settings
[[redirects]]
from = "/"
query = {s = "m"}
to = "/prerender/infrance/index.html"
status = 200

[[redirects]]
from = "/social-security"
query = {s = "m"}
to = "/prerender/infrance/social-security/index.html"
status = 200

[[redirects]]
from = "/*"
query = {s = "m"}
to = "/infrance.html"
status = 200

# Redirect to mon-entreprise in staging and development settings
[[redirects]]
from = "/"
to = "/prerender/mon-entreprise/index.html"
status = 200

[[redirects]]
from = "/sécurité-sociale"
to = "/prerender/mon-entreprise/sécurité-sociale/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/mon-entreprise.html"
status = 200



[context.deploy-preview.environment]
  EN_SITE = "${path}?s=m"
  FR_SITE = "${path}"

[context.production.environment]
  EN_SITE = "https://mycompanyinfrance.fr${path}"
  FR_SITE = "https://mon-entreprise.fr${path}"
